// GENERATED by `npm run build:vercel` from src/. Do not edit by hand.

// src/dashboard.ts
import { existsSync as existsSync3, readFileSync as readFileSync3, statSync } from "node:fs";
import { createServer } from "node:http";
import { extname, isAbsolute, join as join2, relative, resolve } from "node:path";
import { fileURLToPath as fileURLToPath2 } from "node:url";
import { getAddress as getAddress2 } from "viem";
import { z } from "zod";

// src/accounts.ts
import { randomBytes, scrypt, timingSafeEqual } from "node:crypto";

// src/store.ts
import { AsyncLocalStorage } from "node:async_hooks";
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
var PREFIX = "ledgerly:";
var STORE_KEYS = ["state.json", "portfolio.json", "dca.json", "ledger.json", "prepared.json", "profile.json"];
function memoryBackend() {
  const data = /* @__PURE__ */ new Map();
  const counters = /* @__PURE__ */ new Map();
  const locks = /* @__PURE__ */ new Set();
  return {
    name: "memory",
    async load(keys) {
      return Object.fromEntries(keys.map((k) => [k, data.has(k) ? structuredClone(data.get(k)) : null]));
    },
    async save(entries) {
      for (const [k, v] of Object.entries(entries)) data.set(k, structuredClone(v));
    },
    async lock(name) {
      if (locks.has(name)) return null;
      locks.add(name);
      return async () => {
        locks.delete(name);
      };
    },
    async incr(key, ttlSeconds) {
      const now = Date.now();
      const c = counters.get(key);
      if (!c || c.exp < now) {
        counters.set(key, { n: 1, exp: now + ttlSeconds * 1e3 });
        return 1;
      }
      return ++c.n;
    },
    async create(key, value) {
      if (data.has(key)) return false;
      data.set(key, structuredClone(value));
      return true;
    },
    async remove(keys) {
      for (const k of keys) data.delete(k);
    }
  };
}
var RELEASE_LOCK = "if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end";
function upstashBackend(url, token) {
  let client2 = null;
  const redis = () => client2 ??= import("@upstash/redis").then((m) => new m.Redis({ url, token }));
  return {
    name: "upstash",
    async load(keys) {
      const r = await redis();
      const values = await r.mget(...keys);
      return Object.fromEntries(keys.map((k, i) => [k, values[i] ?? null]));
    },
    async save(entries, ttlSeconds) {
      if (!Object.keys(entries).length) return;
      const r = await redis();
      if (!ttlSeconds) return void await r.mset(entries);
      const p = r.pipeline();
      for (const [k, v] of Object.entries(entries)) p.set(k, v, { ex: ttlSeconds });
      await p.exec();
    },
    async lock(name, ttlMs) {
      const r = await redis();
      const mine = randomUUID();
      const key = PREFIX + "lock:" + name;
      const ok = await r.set(key, mine, { nx: true, px: ttlMs });
      if (ok !== "OK") return null;
      return async () => {
        await r.eval(RELEASE_LOCK, [key], [mine]).catch(() => void 0);
      };
    },
    async incr(key, ttlSeconds) {
      const r = await redis();
      const n = await r.incr(PREFIX + key);
      if (n === 1) await r.expire(PREFIX + key, ttlSeconds);
      return n;
    },
    async create(key, value) {
      return await (await redis()).set(key, value, { nx: true }) === "OK";
    },
    async remove(keys) {
      if (keys.length) await (await redis()).del(...keys);
    }
  };
}
function pickBackend() {
  if (process.env.LEDGERLY_STORE === "memory") return memoryBackend();
  const url = process.env.UPSTASH_REDIS_REST_URL || process.env.KV_REST_API_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN || process.env.KV_REST_API_TOKEN;
  return url && token ? upstashBackend(url, token) : null;
}
var backend = pickBackend();
var isRemote = () => backend !== null;
var backendName = () => backend?.name ?? "files";
var tenantPrefix = (t) => PREFIX + (t ? `u:${t.id}:` : "");
var als = new AsyncLocalStorage();
function ctx() {
  const c = als.getStore();
  if (!c) throw new Error("Saved state was used outside a request. Wrap the work in withStore().");
  return c;
}
var isUser = () => als.getStore()?.tenant?.kind === "user";
var currentTenant = () => als.getStore()?.tenant;
async function flush(c) {
  if (!backend || !c.dirty.size) return;
  const entries = {};
  for (const k of c.dirty) entries[k] = c.cache.get(k);
  await backend.save(entries);
  c.dirty.clear();
}
async function acquire(name) {
  for (let i = 0; i < 40; i++) {
    const release = await backend.lock(name, 6e4);
    if (release) return release;
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error("Another request is still changing the saved state. Try again in a moment.");
}
async function withStore(fn, opts = {}) {
  if (!backend) {
    if (opts.tenant) throw new Error("Accounts need the hosted (Redis) store so each person stays separate.");
    return fn();
  }
  const prefix = tenantPrefix(opts.tenant);
  const release = opts.lock ? await acquire(opts.tenant ? prefix : "main") : null;
  const c = { cache: /* @__PURE__ */ new Map(), dirty: /* @__PURE__ */ new Set(), prefix, tenant: opts.tenant };
  try {
    const keys = STORE_KEYS.map((k) => c.prefix + k);
    const loaded = await backend.load(keys);
    for (const k of keys) if (loaded[k] !== null && loaded[k] !== void 0) c.cache.set(k, loaded[k]);
    return await als.run(c, fn);
  } finally {
    try {
      await flush(c);
    } finally {
      if (release) await release();
    }
  }
}
var dataPath = (name) => backend ? PREFIX + name : process.env.LEDGERLY_DATA_DIR ? join(process.env.LEDGERLY_DATA_DIR, name) : fileURLToPath(new URL(`../data/${name}`, import.meta.url));
var remoteKey = (c, file) => c.prefix + (file.startsWith(PREFIX) ? file.slice(PREFIX.length) : basename(file));
function readJson(file, fallback) {
  if (backend) {
    const c = ctx();
    const key = remoteKey(c, file);
    return c.cache.has(key) ? structuredClone(c.cache.get(key)) : fallback;
  }
  if (!existsSync(file)) return fallback;
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch {
    return fallback;
  }
}
function writeJson(file, value) {
  if (backend) {
    const c = ctx();
    const key = remoteKey(c, file);
    c.cache.set(key, structuredClone(value));
    c.dirty.add(key);
    return;
  }
  if (!existsSync(dirname(file))) mkdirSync(dirname(file), { recursive: true });
  const tmp = `${file}.tmp`;
  writeFileSync(tmp, JSON.stringify(value, null, 2));
  renameSync(tmp, file);
}
function remote() {
  if (!backend) throw new Error("Accounts need the hosted (Redis) store.");
  return backend;
}
var rawKey = (name) => PREFIX + name;
async function rawGet(name) {
  const k = rawKey(name);
  return (await remote().load([k]))[k] ?? null;
}
var rawCreate = (name, value) => remote().create(rawKey(name), value);
async function rawRemove(names, tenant) {
  const keys = names.map(rawKey);
  if (tenant) keys.push(...STORE_KEYS.map((k) => tenantPrefix(tenant) + k));
  await remote().remove(keys);
}
var localCounters = /* @__PURE__ */ new Map();
async function withinRateLimit(key, limit, windowSeconds) {
  if (backend) return await backend.incr("rl:" + key, windowSeconds) <= limit;
  const now = Date.now();
  const c = localCounters.get(key);
  if (!c || c.exp < now) {
    localCounters.set(key, { n: 1, exp: now + windowSeconds * 1e3 });
    return true;
  }
  return ++c.n <= limit;
}
var version = 0;
var bumpVersion = () => ++version;
var getVersion = () => version;

// src/accounts.ts
var num = (v, d) => v && !Number.isNaN(Number(v)) && Number(v) >= 0 ? Number(v) : d;
var usersEnabled = () => process.env.USERS_ENABLED === "yes" && isRemote() && Boolean(process.env.AUTH_SECRET);
var USER_POLICY = {
  maxPerTx: num(process.env.USER_MAX_PER_TX, 25),
  maxPerDay: num(process.env.USER_MAX_PER_DAY, 100),
  approvalThreshold: 0
  // 0 means every action is held for that person to sign
};
var allowLiveSells = () => process.env.USERS_ALLOW_SELLS === "yes";
var USER_LIMITS = {
  signupsPerIpPerHour: 3,
  signupsPerDay: () => num(process.env.USERS_MAX_SIGNUPS_PER_DAY, 100),
  loginsPerIpPer5Min: 15,
  loginsPerNamePer15Min: 8,
  actionsPerDay: 2e3
};
var USER_ALLOWED = /* @__PURE__ */ new Set([
  "GET /api/state",
  "GET /api/wallet",
  "GET /api/portfolio/config",
  "GET /api/registry",
  "GET /api/quotes",
  "GET /api/research",
  "POST /api/dca",
  "POST /api/dca/run",
  "POST /api/dca/cancel",
  "POST /api/payee",
  "POST /api/pay",
  "POST /api/portfolio/targets",
  "POST /api/portfolio/rebalance",
  "POST /api/reject",
  "POST /api/wallet/prepare",
  "POST /api/wallet/complete",
  "POST /api/account/wallet"
]);
function validateUsername(input) {
  const u = typeof input === "string" ? input.trim().toLowerCase() : "";
  if (!/^[a-z0-9_]{3,24}$/.test(u)) throw new Error("Username must be 3 to 24 characters: letters, numbers and underscores.");
  return u;
}
function validatePassword(input, username) {
  const p = typeof input === "string" ? input : "";
  if (p.length < 10) throw new Error("Password must be at least 10 characters.");
  if (p.length > 128) throw new Error("Password must be at most 128 characters.");
  if (p.toLowerCase().includes(username)) throw new Error("Password must not contain your username.");
  return p;
}
var kdf = (password, salt) => new Promise((resolve2, reject) => scrypt(password, salt, 64, { N: 16384, r: 8, p: 1 }, (err, key) => err ? reject(err) : resolve2(key)));
var DUMMY_SALT = randomBytes(16);
var recordName = (username) => "acct:" + username;
async function hashPassword(password) {
  const salt = randomBytes(16);
  return { salt: salt.toString("base64"), hash: (await kdf(password, salt)).toString("base64") };
}
async function createAccount(usernameInput, passwordInput) {
  const username = validateUsername(usernameInput);
  const password = validatePassword(passwordInput, username);
  const record2 = { id: randomBytes(12).toString("base64url"), username, ...await hashPassword(password), createdAt: (/* @__PURE__ */ new Date()).toISOString() };
  if (!await rawCreate(recordName(username), record2)) throw new Error("That username is taken.");
  return { id: record2.id, username };
}
async function checkLogin(usernameInput, password) {
  const username = typeof usernameInput === "string" ? usernameInput.trim().toLowerCase() : "";
  const pw = typeof password === "string" ? password : "";
  const rec = /^[a-z0-9_]{3,24}$/.test(username) ? await rawGet(recordName(username)) : null;
  const salt = rec ? Buffer.from(rec.salt, "base64") : DUMMY_SALT;
  const got = await kdf(pw.slice(0, 128), salt);
  if (!rec) return null;
  const want = Buffer.from(rec.hash, "base64");
  return got.length === want.length && timingSafeEqual(got, want) ? { id: rec.id, username: rec.username } : null;
}
async function removeAccount(username, id) {
  await rawRemove([recordName(username)], { kind: "user", id });
}
async function signupAllowed(ip) {
  if (!await withinRateLimit("acct-new-ip:" + ip, USER_LIMITS.signupsPerIpPerHour, 3600)) return { ok: false, message: "Too many sign-ups from this connection. Try again in an hour." };
  if (!await withinRateLimit("acct-new:" + (/* @__PURE__ */ new Date()).toISOString().slice(0, 10), USER_LIMITS.signupsPerDay(), 86400)) return { ok: false, message: "Sign-ups are full for today. Please come back tomorrow." };
  return { ok: true };
}
async function loginAllowed(ip, username) {
  return await withinRateLimit("acct-login-ip:" + ip, USER_LIMITS.loginsPerIpPer5Min, 300) && await withinRateLimit("acct-login:" + username.toLowerCase(), USER_LIMITS.loginsPerNamePer15Min, 900);
}

// src/approvals.ts
import { randomUUID as randomUUID2 } from "node:crypto";
var APPROVAL_TTL_MS = 24 * 36e5;
var FILE = dataPath("state.json");
var load = () => {
  const s = readJson(FILE, {});
  return { payees: s.payees ?? {}, pending: s.pending ?? [] };
};
var save = (s) => writeJson(FILE, s);
function addPayee(address2, label) {
  const s = load();
  s.payees[address2.toLowerCase()] = label;
  save(s);
}
var listPayees = () => Object.entries(load().payees).map(([address2, label]) => ({ address: address2, label }));
var payeeSet = () => new Set(Object.keys(load().payees));
var isExpired = (p, now = Date.now()) => now - new Date(p.createdAt).getTime() > APPROVAL_TTL_MS;
function addPending(item) {
  const s = load();
  const p = { id: randomUUID2().slice(0, 8), createdAt: (/* @__PURE__ */ new Date()).toISOString(), ...item };
  s.pending.push(p);
  save(s);
  return p;
}
function listPending() {
  const s = load();
  const live = s.pending.filter((p) => !isExpired(p));
  if (live.length !== s.pending.length) save({ ...s, pending: live });
  return live;
}
function getPending(id) {
  const p = load().pending.find((x) => x.id === id);
  return p && !isExpired(p) ? p : void 0;
}
function takePending(id) {
  const s = load();
  const p = s.pending.find((x) => x.id === id);
  if (!p) return void 0;
  save({ ...s, pending: s.pending.filter((x) => x.id !== id) });
  return isExpired(p) ? void 0 : p;
}

// src/ledger.ts
import { appendFileSync, existsSync as existsSync2, mkdirSync as mkdirSync2, readFileSync as readFileSync2 } from "node:fs";
import { dirname as dirname2 } from "node:path";
var DEFAULT_FILE = dataPath("ledger.jsonl");
var REMOTE_KEY = dataPath("ledger.json");
var REMOTE_MAX = 1e3;
function record(entry2, file = DEFAULT_FILE) {
  const full = { ts: (/* @__PURE__ */ new Date()).toISOString(), ...entry2 };
  if (isRemote() && file === DEFAULT_FILE) {
    writeJson(REMOTE_KEY, [...readJson(REMOTE_KEY, []), full].slice(-REMOTE_MAX));
    return full;
  }
  if (!existsSync2(dirname2(file))) mkdirSync2(dirname2(file), { recursive: true });
  appendFileSync(file, JSON.stringify(full) + "\n");
  return full;
}
function readAll(file = DEFAULT_FILE) {
  if (isRemote() && file === DEFAULT_FILE) return readJson(REMOTE_KEY, []);
  if (!existsSync2(file)) return [];
  return readFileSync2(file, "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l));
}
function spentToday(entries, now = /* @__PURE__ */ new Date()) {
  const day = now.toISOString().slice(0, 10);
  return entries.filter((e) => e.executed && !e.dryRun && e.ts.startsWith(day)).reduce((s, e) => s + (e.amountUsd ?? 0), 0);
}

// src/chain.ts
import { createPublicClient, createWalletClient, defineChain, erc20Abi, http, parseUnits } from "viem";
import { privateKeyToAccount } from "viem/accounts";

// src/config.ts
import "dotenv/config";
var num2 = (v, d) => v && !Number.isNaN(Number(v)) ? Number(v) : d;
var network = process.env.NETWORK === "mainnet" ? "mainnet" : "testnet";
function tradingOffReasonFor(env) {
  if (env.NETWORK !== "mainnet") return "Set NETWORK=mainnet. Ledgerly only trades on Robinhood Chain mainnet.";
  if (env.DRY_RUN === "true") return "DRY_RUN=true is set, which switches trading off. Remove it to trade.";
  if (env.LIVE_MAINNET !== "yes") return "Trading is switched off. Set LIVE_MAINNET=yes to turn it on.";
  return null;
}
var tradingOffReason = tradingOffReasonFor(process.env);
var config = {
  network,
  /** True when real trades and payments are switched on. */
  live: tradingOffReason === null,
  servApiKey: process.env.SERV_API_KEY ?? "",
  servModel: process.env.SERV_MODEL || "gpt-5.4-mini",
  privateKey: process.env.AGENT_PRIVATE_KEY,
  slippageBps: Math.min(500, Math.max(1, num2(process.env.SLIPPAGE_BPS, 50))),
  // Defaults to USDG on mainnet (docs.robinhood.com/chain/contracts).
  paymentToken: process.env.PAYMENT_TOKEN_ADDRESS || (process.env.NETWORK === "mainnet" ? "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168" : void 0),
  paymentDecimals: num2(process.env.PAYMENT_TOKEN_DECIMALS, 6),
  policy: {
    maxPerTx: num2(process.env.MAX_PER_TX, 50),
    maxPerDay: num2(process.env.MAX_PER_DAY, 200),
    approvalThreshold: num2(process.env.APPROVAL_THRESHOLD, 25)
  }
};

// src/chain.ts
var rhTestnet = defineChain({
  id: 46630,
  name: "Robinhood Chain Testnet",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: ["https://rpc.testnet.chain.robinhood.com"] } },
  blockExplorers: { default: { name: "Explorer", url: "https://explorer.testnet.chain.robinhood.com" } }
});
var rhMainnet = defineChain({
  id: 4663,
  name: "Robinhood Chain",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: ["https://rpc.mainnet.chain.robinhood.com"] } },
  blockExplorers: { default: { name: "Blockscout", url: "https://robinhoodchain.blockscout.com" } }
});
var chain = config.network === "mainnet" ? rhMainnet : rhTestnet;
var publicClient = createPublicClient({ chain, transport: http() });
var mainnetClient = createPublicClient({ chain: rhMainnet, transport: http() });
function walletClient() {
  if (isUser()) throw new Error("Only the owner has a server-side wallet. Accounts sign with their own wallet.");
  if (!config.privateKey) throw new Error("AGENT_PRIVATE_KEY is not set.");
  return createWalletClient({ account: privateKeyToAccount(config.privateKey), chain, transport: http() });
}
function walletAddress() {
  if (isUser()) return readJson(dataPath("profile.json"), {}).wallet;
  return config.privateKey ? privateKeyToAccount(config.privateKey).address : void 0;
}
async function tokenBalance() {
  const addr = walletAddress();
  if (!addr || !config.paymentToken) return "unconfigured";
  const raw = await publicClient.readContract({
    address: config.paymentToken,
    abi: erc20Abi,
    functionName: "balanceOf",
    args: [addr]
  });
  return (Number(raw) / 10 ** config.paymentDecimals).toString();
}
async function sendPayment(to, amountUsd) {
  if (isUser()) throw new Error("Only the owner has a server-side wallet. Accounts sign with their own wallet.");
  if (!config.privateKey || !config.paymentToken) {
    throw new Error("AGENT_PRIVATE_KEY and PAYMENT_TOKEN_ADDRESS must be set for live payments.");
  }
  const wallet = createWalletClient({ account: privateKeyToAccount(config.privateKey), chain, transport: http() });
  return wallet.writeContract({
    address: config.paymentToken,
    abi: erc20Abi,
    functionName: "transfer",
    args: [to, parseUnits(amountUsd.toString(), config.paymentDecimals)]
  });
}

// src/mode.ts
var policy = () => isUser() ? USER_POLICY : config.policy;

// src/guardrails.ts
function evaluate(policy2, req, spentTodayUsd, allowlist) {
  if (!Number.isFinite(req.amountUsd) || req.amountUsd <= 0) {
    return { decision: "deny", reason: "Amount must be a positive number." };
  }
  if (req.to && !allowlist.has(req.to.toLowerCase())) {
    return { decision: "deny", reason: `Recipient ${req.to} is not on the allowlist.` };
  }
  if (req.amountUsd > policy2.maxPerTx) {
    return { decision: "deny", reason: `Amount ${req.amountUsd} exceeds per-transaction cap ${policy2.maxPerTx}.` };
  }
  if (spentTodayUsd + req.amountUsd > policy2.maxPerDay) {
    return {
      decision: "deny",
      reason: `Would bring today's spend to ${spentTodayUsd + req.amountUsd}, over the daily cap ${policy2.maxPerDay}.`
    };
  }
  if (req.amountUsd > policy2.approvalThreshold) {
    return {
      decision: "needs_approval",
      reason: `Amount ${req.amountUsd} is above the auto-approve threshold ${policy2.approvalThreshold}.`
    };
  }
  return { decision: "allow" };
}
function ruleFor(v) {
  return v.decision === "allow" ? "Within the per-transaction cap, the daily cap and the approval threshold." : v.reason;
}

// src/reasoning.ts
import OpenAI from "openai";
var client = new OpenAI({
  apiKey: config.servApiKey || "missing",
  baseURL: "https://inference-api.openserv.ai/v1"
});
var SYSTEM = `You are Ledgerly's treasury analyst. You are given a proposed money movement and the policy verdict already computed by a deterministic guardrail engine. Explain in 2-3 plain sentences why the action is reasonable or not, and flag any risk. Never override the verdict.`;
var lastError = null;
function servTools(shadowHint) {
  const tools = [{ type: "function", function: { name: "serv_prompt_guard" } }];
  if (shadowHint) {
    tools.push({
      type: "function",
      function: {
        name: "serv_shadow_agent",
        parameters: {
          type: "object",
          properties: {
            hint: { type: "string", default: shadowHint },
            max_iterations: { type: "integer", default: 3 }
          }
        }
      }
    });
  }
  return tools;
}
async function ask(system, user, opts = {}) {
  if (!config.servApiKey) return null;
  try {
    const res = await client.chat.completions.create({
      model: config.servModel,
      max_completion_tokens: opts.maxTokens ?? 300,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user }
      ],
      tools: servTools(opts.shadowHint)
    });
    lastError = null;
    return res.choices[0]?.message?.content?.trim() || null;
  } catch (err) {
    lastError = err.message;
    console.error("SERV reasoning call failed:", lastError);
    return null;
  }
}
function usableExplanation(text) {
  if (!text) return false;
  const t = text.trim();
  return t.length >= 40 && !/^(i\s+(can['’]?t|cannot|won['’]?t|am unable|['’]?m unable)|sorry|as an ai)/i.test(t);
}
async function explain(context) {
  if (!config.servApiKey) return `(no SERV_API_KEY set) ${context}`;
  const reply = await ask(SYSTEM, context);
  return usableExplanation(reply) ? reply : `${context} (reasoning unavailable: ${lastError ?? "the model gave no usable explanation"})`;
}

// src/treasury.ts
var off = () => tradingOffReason ?? "Trading is switched off.";
var entry = (req, verdict, executed, reasoning, extra = {}) => record({ module: req.module, action: req.memo, amountUsd: req.amountUsd, to: req.to, verdict, executed, reasoning, ...extra });
async function execute(req, reasoning, verdict, rule) {
  if (isUser()) throw new Error('Accounts sign their own transactions, so nothing is sent from the server. Use "Sign with my wallet".');
  if (!config.live) throw new Error(off());
  try {
    const txHash = await sendPayment(req.to, req.amountUsd);
    entry(req, verdict, true, reasoning, { txHash, rule });
    return { status: "executed", txHash, message: `Paid ${req.amountUsd} to ${req.to}. ${reasoning}` };
  } catch (err) {
    const msg = err.message;
    entry(req, verdict, false, `Failed: ${msg}`, { rule });
    return { status: "failed", message: `Payment failed: ${msg}` };
  }
}
async function pay(req) {
  if (!config.live) return { status: "denied", message: off() };
  const verdict = evaluate(policy(), req, spentToday(readAll()), payeeSet());
  const context = `Module: ${req.module}. Memo: ${req.memo}. Amount: ${req.amountUsd}. To: ${req.to}. Verdict: ${verdict.decision}${"reason" in verdict ? ` (${verdict.reason})` : ""}.`;
  const reasoning = await explain(context);
  const rule = ruleFor(verdict);
  if (verdict.decision === "deny") {
    entry(req, "deny", false, reasoning, { rule });
    return { status: "denied", message: `Denied: ${verdict.reason}` };
  }
  if (verdict.decision === "needs_approval") {
    const p = addPending({ kind: "pay", req });
    entry(req, "needs_approval", false, reasoning, { rule });
    return { status: "pending_approval", approvalId: p.id, message: `Needs human approval (${verdict.reason}). Approval id: ${p.id}` };
  }
  return execute(req, reasoning, "allow", rule);
}
async function executeApprovedPayment(req, approvalId) {
  const recheck = evaluate({ ...policy(), approvalThreshold: Infinity }, req, spentToday(readAll()), payeeSet());
  if (recheck.decision === "deny") {
    entry(req, "deny", false, "Approved but blocked on re-check.", { rule: ruleFor(recheck) });
    return { status: "denied", message: `Blocked on re-check: ${recheck.reason}` };
  }
  return execute(req, `Approved by a human (id ${approvalId}).`, "needs_approval", "Re-checked against the caps and allowlist at the moment of approval; still within them.");
}

// src/trading.ts
import { formatUnits as formatUnits2, parseUnits as parseUnits3 } from "viem";

// src/market.ts
var BASE = "https://api.robinhood.com/rhj";
function parseQuote(symbol, body) {
  const q = body?.quotes?.[0];
  if (!q) throw new Error(`No quote returned for ${symbol}`);
  const bid = Number(q.bid);
  const ask2 = Number(q.ask);
  if (!Number.isFinite(bid) || !Number.isFinite(ask2) || bid <= 0 || ask2 <= 0) {
    throw new Error(`Invalid bid/ask for ${symbol}`);
  }
  const deployments = q.deployments;
  return {
    symbol: String(q.tokenSymbol ?? symbol).toUpperCase(),
    bid,
    ask: ask2,
    mid: (bid + ask2) / 2,
    dailyHigh: Number(q.dailyHigh) || ask2,
    dailyLow: Number(q.dailyLow) || bid,
    halted: q.isTradingHalt === true,
    generatedAt: String(q.generatedAt ?? ""),
    contract: deployments?.find((d) => d.chainId === 4663)?.contractAddress
  };
}
async function fetchWithRetry(url, tries = 3) {
  for (let i = 0; i < tries; i++) {
    try {
      return await fetch(url, { signal: AbortSignal.timeout(1e4) });
    } catch {
      if (i < tries - 1) await new Promise((r) => setTimeout(r, 250 * (i + 1)));
    }
  }
  throw new Error("Could not reach the Robinhood price service. Please try again in a moment.");
}
async function getQuote(symbol) {
  const sym = symbol.trim().toUpperCase();
  if (!/^[A-Z0-9.]{1,10}$/.test(sym)) throw new Error(`Invalid symbol: ${symbol}`);
  const res = await fetchWithRetry(`${BASE}/prices/${sym}`);
  if (!res.ok) throw new Error(`Price API returned ${res.status} for ${sym}`);
  return parseQuote(sym, await res.json());
}

// src/swap.ts
import { erc20Abi as erc20Abi2, formatUnits, parseAbi, parseUnits as parseUnits2 } from "viem";
var ADDR = {
  usdg: "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
  quoterV2: "0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7",
  swapRouter02: "0xcaf681a66d020601342297493863e78c959e5cb2"
};
var USDG_DECIMALS = 6;
var STOCK_DECIMALS = 18;
var FEE_TIERS = [100, 500, 3e3, 1e4];
var MAX_PRICE_DEVIATION = 0.03;
var quoterAbi = parseAbi([
  "function quoteExactInputSingle((address tokenIn,address tokenOut,uint256 amountIn,uint24 fee,uint160 sqrtPriceLimitX96)) returns (uint256 amountOut,uint160 sqrtPriceX96After,uint32 initializedTicksCrossed,uint256 gasEstimate)"
]);
var routerAbi = parseAbi([
  "function exactInputSingle((address tokenIn,address tokenOut,uint24 fee,address recipient,uint256 amountIn,uint256 amountOutMinimum,uint160 sqrtPriceLimitX96)) payable returns (uint256 amountOut)"
]);
function pickBest(cands, amountUsd, refPriceUsd) {
  let best = null;
  for (const c of cands) {
    const tokens = Number(formatUnits(c.amountOut, STOCK_DECIMALS));
    if (tokens <= 0) continue;
    const implied = amountUsd / tokens;
    if (Math.abs(implied / refPriceUsd - 1) > MAX_PRICE_DEVIATION) continue;
    if (!best || c.amountOut > best.amountOut) best = { fee: c.fee, amountOut: c.amountOut, tokens, impliedPriceUsd: implied };
  }
  return best;
}
function minOut(amountOut, slippageBps) {
  return amountOut * BigInt(1e4 - slippageBps) / 10000n;
}
async function quoteBuy(tokenOut, amountUsd, refPriceUsd) {
  const amountIn = parseUnits2(amountUsd.toString(), USDG_DECIMALS);
  const results = await Promise.all(
    FEE_TIERS.map(async (fee) => {
      try {
        const { result } = await mainnetClient.simulateContract({
          address: ADDR.quoterV2,
          abi: quoterAbi,
          functionName: "quoteExactInputSingle",
          args: [{ tokenIn: ADDR.usdg, tokenOut, amountIn, fee, sqrtPriceLimitX96: 0n }]
        });
        return { fee, amountOut: result[0] };
      } catch {
        return null;
      }
    })
  );
  const route2 = pickBest(results.filter((r) => r !== null), amountUsd, refPriceUsd);
  if (!route2) throw new Error("No pool returned a sane quote (empty pool or price mismatch).");
  return route2;
}
async function buyToken(tokenOut, amountUsd, route2) {
  if (config.network !== "mainnet") throw new Error("Live swaps are only supported on mainnet (NETWORK=mainnet).");
  const wallet = walletClient();
  const owner = wallet.account.address;
  const amountIn = parseUnits2(amountUsd.toString(), USDG_DECIMALS);
  const balance = await mainnetClient.readContract({ address: ADDR.usdg, abi: erc20Abi2, functionName: "balanceOf", args: [owner] });
  if (balance < amountIn) throw new Error(`Insufficient USDG: have ${formatUnits(balance, USDG_DECIMALS)}, need ${amountUsd}.`);
  let approveTx;
  const allowance = await mainnetClient.readContract({ address: ADDR.usdg, abi: erc20Abi2, functionName: "allowance", args: [owner, ADDR.swapRouter02] });
  if (allowance < amountIn) {
    approveTx = await wallet.writeContract({ address: ADDR.usdg, abi: erc20Abi2, functionName: "approve", args: [ADDR.swapRouter02, amountIn] });
    const r2 = await mainnetClient.waitForTransactionReceipt({ hash: approveTx });
    if (r2.status !== "success") throw new Error("USDG approval reverted.");
  }
  const swapTx = await wallet.writeContract({
    address: ADDR.swapRouter02,
    abi: routerAbi,
    functionName: "exactInputSingle",
    args: [{ tokenIn: ADDR.usdg, tokenOut, fee: route2.fee, recipient: owner, amountIn, amountOutMinimum: minOut(route2.amountOut, config.slippageBps), sqrtPriceLimitX96: 0n }]
  });
  const r = await mainnetClient.waitForTransactionReceipt({ hash: swapTx });
  if (r.status !== "success") throw new Error(`Swap reverted (tx ${swapTx}).`);
  return { approveTx, swapTx };
}
function pickBestSell(cands, tokenAmount, refPriceUsd) {
  const tokens = Number(formatUnits(tokenAmount, STOCK_DECIMALS));
  if (tokens <= 0) return null;
  let best = null;
  for (const c of cands) {
    const usdOut = Number(formatUnits(c.amountOut, USDG_DECIMALS));
    if (usdOut <= 0) continue;
    const implied = usdOut / tokens;
    if (Math.abs(implied / refPriceUsd - 1) > MAX_PRICE_DEVIATION) continue;
    if (!best || c.amountOut > best.amountOut) best = { fee: c.fee, amountOut: c.amountOut, usdOut, impliedPriceUsd: implied };
  }
  return best;
}
async function quoteSell(tokenIn, tokenAmount, refPriceUsd) {
  const results = await Promise.all(
    FEE_TIERS.map(async (fee) => {
      try {
        const { result } = await mainnetClient.simulateContract({
          address: ADDR.quoterV2,
          abi: quoterAbi,
          functionName: "quoteExactInputSingle",
          args: [{ tokenIn, tokenOut: ADDR.usdg, amountIn: tokenAmount, fee, sqrtPriceLimitX96: 0n }]
        });
        return { fee, amountOut: result[0] };
      } catch {
        return null;
      }
    })
  );
  const route2 = pickBestSell(results.filter((r) => r !== null), tokenAmount, refPriceUsd);
  if (!route2) throw new Error("No pool returned a sane sell quote (empty pool or price mismatch).");
  return route2;
}
async function sellToken(tokenIn, tokenAmount, route2) {
  if (config.network !== "mainnet") throw new Error("Live swaps are only supported on mainnet (NETWORK=mainnet).");
  const wallet = walletClient();
  const owner = wallet.account.address;
  const balance = await mainnetClient.readContract({ address: tokenIn, abi: erc20Abi2, functionName: "balanceOf", args: [owner] });
  if (balance < tokenAmount) throw new Error("Insufficient token balance for this sale.");
  let approveTx;
  const allowance = await mainnetClient.readContract({ address: tokenIn, abi: erc20Abi2, functionName: "allowance", args: [owner, ADDR.swapRouter02] });
  if (allowance < tokenAmount) {
    approveTx = await wallet.writeContract({ address: tokenIn, abi: erc20Abi2, functionName: "approve", args: [ADDR.swapRouter02, tokenAmount] });
    const r2 = await mainnetClient.waitForTransactionReceipt({ hash: approveTx });
    if (r2.status !== "success") throw new Error("Token approval reverted.");
  }
  const swapTx = await wallet.writeContract({
    address: ADDR.swapRouter02,
    abi: routerAbi,
    functionName: "exactInputSingle",
    args: [{ tokenIn, tokenOut: ADDR.usdg, fee: route2.fee, recipient: owner, amountIn: tokenAmount, amountOutMinimum: minOut(route2.amountOut, config.slippageBps), sqrtPriceLimitX96: 0n }]
  });
  const r = await mainnetClient.waitForTransactionReceipt({ hash: swapTx });
  if (r.status !== "success") throw new Error(`Swap reverted (tx ${swapTx}).`);
  return { approveTx, swapTx };
}
function balanceOf(token, owner) {
  return mainnetClient.readContract({ address: token, abi: erc20Abi2, functionName: "balanceOf", args: [owner] });
}

// src/trading.ts
var log = (t, verdict, action, executed, reasoning, txHash, rule) => record({ module: t.module, action, amountUsd: t.amountUsd, verdict, executed, txHash, reasoning, rule });
async function execute2(t, q, rule) {
  if (isUser()) throw new Error('Accounts sign their own transactions, so nothing is sent from the server. Use "Sign with my wallet".');
  const label = `${t.side === "buy" ? "Buy" : "Sell"} ${t.symbol}`;
  const contract = q.contract;
  if (t.side === "buy") {
    const route3 = await quoteBuy(contract, t.amountUsd, q.ask);
    const detail2 = `~${route3.tokens.toFixed(6)} tokens via ${route3.fee / 1e4}% pool @ $${route3.impliedPriceUsd.toFixed(2)} (ask ${q.ask})`;
    const { swapTx: swapTx2 } = await buyToken(contract, t.amountUsd, route3);
    log(t, "allow", `${label}: ${detail2}`, true, t.why, swapTx2, rule);
    return { status: "executed", amountUsd: t.amountUsd, tokens: route3.tokens, txHash: swapTx2, message: `Bought $${t.amountUsd} of ${t.symbol}, ${detail2}. tx ${swapTx2}` };
  }
  const wanted = t.amountUsd / q.mid;
  let held;
  const owner = walletAddress();
  if (owner) held = Number(formatUnits2(await balanceOf(contract, owner), 18));
  else throw new Error("AGENT_PRIVATE_KEY is not set.");
  const tokens = Math.min(wanted, held);
  if (tokens <= 0) return { status: "skipped", message: `Nothing to sell: no ${t.symbol} held.` };
  const usdEstimate = Math.round(tokens * q.mid * 100) / 100;
  const amountIn = parseUnits3(tokens.toFixed(18), 18);
  const route2 = await quoteSell(contract, amountIn, q.bid);
  const detail = `~${tokens.toFixed(6)} tokens for ~$${route2.usdOut.toFixed(2)} via ${route2.fee / 1e4}% pool @ $${route2.impliedPriceUsd.toFixed(2)} (bid ${q.bid})`;
  const { swapTx } = await sellToken(contract, amountIn, route2);
  log(t, "allow", `${label}: ${detail}`, true, t.why, swapTx, rule);
  return { status: "executed", amountUsd: usdEstimate, tokens, txHash: swapTx, message: `Sold ${detail}. tx ${swapTx}` };
}
async function requestTrade(t, opts = {}) {
  const label = `${t.side === "buy" ? "Buy" : "Sell"} ${t.symbol}`;
  try {
    if (!config.live) return { status: "denied", message: tradingOffReason ?? "Trading is switched off." };
    if (isUser() && t.side === "sell" && !allowLiveSells()) {
      log(t, "deny", label, false, "Live selling is not switched on for accounts yet.");
      return { status: "denied", message: "Live selling and rebalancing are not switched on for accounts yet. Buying is available." };
    }
    const q = await getQuote(t.symbol);
    if (q.halted) {
      log(t, "allow", `Skip ${label}`, false, "Trading is halted for this asset.");
      return { status: "skipped", message: `${t.symbol} trading is halted.` };
    }
    if (!q.contract) {
      log(t, "allow", `Skip ${label}`, false, "No Robinhood Chain deployment found for this symbol.");
      return { status: "error", message: `${t.symbol} has no Robinhood Chain deployment.` };
    }
    const rules = opts.approved ? { ...policy(), approvalThreshold: Infinity } : policy();
    const verdict = evaluate(rules, { amountUsd: t.amountUsd }, spentToday(readAll()), /* @__PURE__ */ new Set());
    if (verdict.decision === "deny") {
      log(t, "deny", label, false, t.why, void 0, ruleFor(verdict));
      return { status: "denied", amountUsd: t.amountUsd, message: `Denied: ${verdict.reason}` };
    }
    if (verdict.decision === "needs_approval") {
      const p = addPending({ kind: "trade", trade: t });
      log(t, "needs_approval", label, false, t.why, void 0, ruleFor(verdict));
      return { status: "pending_approval", approvalId: p.id, amountUsd: t.amountUsd, message: `Held for approval (${verdict.reason}) id ${p.id}` };
    }
    const rule = opts.approved ? "Approved by a human; re-checked against the caps at the moment of approval." : ruleFor(verdict);
    const result = await execute2(t, q, rule);
    bumpVersion();
    return result;
  } catch (err) {
    const msg = err.message;
    log(t, "allow", label, false, `Error: ${msg}`);
    return { status: "error", message: msg };
  }
}

// src/approve.ts
async function approveAny(id) {
  if (isUser()) return { status: "denied", message: 'Accounts approve by signing with their own wallet. Use "Sign with my wallet".' };
  const p = takePending(id);
  if (!p) return { status: "denied", message: `No pending action with id ${id}, or it expired (approvals last 24 hours).` };
  if (p.kind === "pay") return executeApprovedPayment(p.req, p.id);
  return requestTrade(p.trade, { approved: true });
}
function rejectAny(id) {
  const p = takePending(id);
  if (!p) return { status: "denied", message: `No pending action with id ${id}, or it expired.` };
  const detail = p.kind === "pay" ? { module: p.req.module, action: p.req.memo, amountUsd: p.req.amountUsd, to: p.req.to } : { module: p.trade.module, action: `${p.trade.side === "buy" ? "Buy" : "Sell"} ${p.trade.symbol}`, amountUsd: p.trade.amountUsd };
  record({ ...detail, verdict: "deny", executed: false, reasoning: "Rejected by a human." });
  return { status: "rejected", message: "Rejected. Nothing was executed." };
}

// src/auth.ts
import { createHash, createHmac, timingSafeEqual as timingSafeEqual2 } from "node:crypto";
var COOKIE = "ledgerly_session";
var MIN_PASSWORD = 12;
var sessionSeconds = () => Math.min(7 * 24, Math.max(1, Number(process.env.SESSION_HOURS) || 12)) * 3600;
var hosted = () => Boolean(process.env.VERCEL);
var authRequired = () => Boolean(process.env.DASHBOARD_PASSWORD);
function authConfigProblem() {
  if (!hosted()) return null;
  const p = process.env.DASHBOARD_PASSWORD;
  if (!p) return "Set DASHBOARD_PASSWORD in the Vercel project settings. The dashboard will not run without a login.";
  if (p.length < MIN_PASSWORD) return `DASHBOARD_PASSWORD is too short. Use at least ${MIN_PASSWORD} characters (a long random one is best).`;
  return null;
}
var digest = (s) => createHash("sha256").update(s).digest();
var safeEqual = (a, b) => timingSafeEqual2(digest(a), digest(b));
var checkPassword = (input) => typeof input === "string" && input.length > 0 && authRequired() && safeEqual(input, process.env.DASHBOARD_PASSWORD);
var secret = () => process.env.AUTH_SECRET || "ledgerly-session:" + digest(process.env.DASHBOARD_PASSWORD ?? "").toString("hex");
var sign = (payload) => createHmac("sha256", secret()).update(payload).digest("base64url");
function makeToken(nowMs = Date.now()) {
  const exp = Math.floor(nowMs / 1e3) + sessionSeconds();
  return `${exp}.${sign(String(exp))}`;
}
function verifyToken(token, nowMs = Date.now()) {
  if (!token) return false;
  const [exp, sig] = token.split(".");
  if (!exp || !sig || !/^\d+$/.test(exp)) return false;
  if (Number(exp) < nowMs / 1e3) return false;
  return safeEqual(sig, sign(exp));
}
function parseCookies(header) {
  const out = {};
  for (const part of (header ?? "").split(";")) {
    const i = part.indexOf("=");
    if (i > 0) out[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim());
  }
  return out;
}
var isAuthed = (req) => verifyToken(parseCookies(req.headers.cookie)[COOKIE]);
var flags = (secure) => `HttpOnly; SameSite=Strict; Path=/${secure ? "; Secure" : ""}`;
var sessionCookie = (token, secure) => `${COOKIE}=${token}; ${flags(secure)}; Max-Age=${sessionSeconds()}`;
var clearedCookie = (secure) => `${COOKIE}=; ${flags(secure)}; Max-Age=0`;
function cronAuthorized(req) {
  const s = process.env.CRON_SECRET;
  const h = req.headers.authorization;
  return Boolean(s) && typeof h === "string" && safeEqual(h, `Bearer ${s}`);
}
function clientId(req) {
  const fwd = req.headers["x-forwarded-for"];
  const first = (Array.isArray(fwd) ? fwd[0] : fwd)?.split(",")[0]?.trim();
  return first || req.socket.remoteAddress || "unknown";
}
function sameOrigin(req) {
  const origin = req.headers.origin;
  if (origin) {
    try {
      return new URL(origin).host === req.headers.host;
    } catch {
      return false;
    }
  }
  const site = req.headers["sec-fetch-site"];
  return !site || site === "same-origin" || site === "none";
}
var USER_COOKIE = "ledgerly_user";
var USER_SESSION_SECONDS = 7 * 24 * 3600;
var userSign = (id, exp) => createHmac("sha256", secret()).update(`user:${id}.${exp}`).digest("base64url");
function makeUserToken(id, nowMs = Date.now()) {
  const exp = String(Math.floor(nowMs / 1e3) + USER_SESSION_SECONDS);
  return `${id}.${exp}.${userSign(id, exp)}`;
}
function verifyUserToken(token, nowMs = Date.now()) {
  if (!token) return null;
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [id, exp, sig] = parts;
  if (!/^[A-Za-z0-9_-]{8,32}$/.test(id) || !/^\d+$/.test(exp) || !sig) return null;
  if (Number(exp) < nowMs / 1e3) return null;
  return safeEqual(sig, userSign(id, exp)) ? id : null;
}
var userIdFrom = (req) => verifyUserToken(parseCookies(req.headers.cookie)[USER_COOKIE]);
var userCookie = (token, secure) => `${USER_COOKIE}=${token}; ${flags(secure)}; Max-Age=${USER_SESSION_SECONDS}`;
var clearedUserCookie = (secure) => `${USER_COOKIE}=; ${flags(secure)}; Max-Age=0`;

// src/dca.ts
import { randomUUID as randomUUID3 } from "node:crypto";
var MIN_MULT = 0.5;
var MAX_MULT = 1.5;
var FILE2 = dataPath("dca.json");
var load2 = () => readJson(FILE2, []);
var save2 = (plans) => writeJson(FILE2, plans);
var listPlans = () => load2();
function createPlan(symbol, amountUsd, intervalHours) {
  if (!/^[A-Za-z0-9.]{1,10}$/.test(symbol.trim())) throw new Error(`Invalid symbol: ${symbol}`);
  const plan = {
    id: randomUUID3().slice(0, 8),
    symbol: symbol.trim().toUpperCase(),
    amountUsd,
    intervalHours,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    lastRunAt: null,
    active: true
  };
  save2([...load2(), plan]);
  return plan;
}
function cancelPlan(id) {
  const plans = load2();
  const p = plans.find((x) => x.id === id);
  if (!p) return false;
  p.active = false;
  save2(plans);
  return true;
}
function isDue(plan, now = /* @__PURE__ */ new Date()) {
  if (!plan.active) return false;
  if (!plan.lastRunAt) return true;
  return now.getTime() - new Date(plan.lastRunAt).getTime() >= plan.intervalHours * 36e5;
}
var DEFAULT = { action: "buy", multiplier: 1, why: "Default: buy the planned amount.", source: "default" };
function parseDecision(text) {
  if (!text) return DEFAULT;
  const json = text.match(/\{[\s\S]*\}/)?.[0];
  if (!json) return DEFAULT;
  try {
    const o = JSON.parse(json);
    const action = o.action === "skip" ? "skip" : "buy";
    const m = Number(o.multiplier);
    const multiplier = Number.isFinite(m) ? Math.min(MAX_MULT, Math.max(MIN_MULT, m)) : 1;
    return { action, multiplier, why: String(o.why ?? o.reason ?? "").slice(0, 400) || "No explanation given.", source: "serv" };
  } catch {
    return DEFAULT;
  }
}
var SYSTEM2 = `You decide whether a scheduled dollar-cost-averaging buy of a tokenized stock should proceed. Reply with ONLY a JSON object: {"action":"buy"|"skip","multiplier":number between 0.5 and 1.5,"why":"one or two plain sentences"}. Default to buying the planned amount (multiplier 1). Buy a little more (up to 1.5) when the price is near the bottom of its daily range, a little less (down to 0.5) near the top. Skip only for a clear reason. Never suggest chasing momentum or trying to time the market. This is a disciplined recurring purchase.`;
async function decide(plan, q) {
  const pos = q.dailyHigh > q.dailyLow ? (q.mid - q.dailyLow) / (q.dailyHigh - q.dailyLow) : 0.5;
  const user = `Symbol ${q.symbol}. Planned buy $${plan.amountUsd}. Bid ${q.bid}, ask ${q.ask}. Daily low ${q.dailyLow}, high ${q.dailyHigh}. Price sits at ${(pos * 100).toFixed(0)}% of today's range.`;
  return parseDecision(
    await ask(SYSTEM2, user, {
      maxTokens: 400,
      shadowHint: 'The reply must be only a JSON object with "action" ("buy" or "skip"), "multiplier" (a number from 0.5 to 1.5) and "why" (one or two plain sentences).'
    })
  );
}
async function runPlan(plan, now = /* @__PURE__ */ new Date()) {
  const base = { planId: plan.id, symbol: plan.symbol };
  const skip = (reasoning, rule) => record({ module: "dca", action: `Skip ${plan.symbol}`, verdict: "allow", executed: false, reasoning, rule });
  try {
    const q = await getQuote(plan.symbol);
    if (q.halted) {
      skip("Trading is halted for this asset.", "Robinhood market status: halted.");
      return { ...base, outcome: "skipped", message: "Skipped: trading halted." };
    }
    const d = await decide(plan, q);
    if (d.action === "skip") {
      skip(d.why);
      return { ...base, outcome: "skipped", message: `Skipped: ${d.why}` };
    }
    const amountUsd = Math.round(plan.amountUsd * d.multiplier * 100) / 100;
    const r = await requestTrade({ side: "buy", symbol: plan.symbol, amountUsd, module: "dca", why: `${d.why} [${d.source}, x${d.multiplier}]` });
    const outcome = r.status === "executed" ? "bought_live" : r.status === "pending_approval" ? "pending_approval" : r.status === "denied" ? "denied" : r.status === "skipped" ? "skipped" : "error";
    return { ...base, outcome, amountUsd, estTokens: r.tokens, txHash: r.txHash, approvalId: r.approvalId, message: `${r.message} ${r.status === "executed" ? d.why : ""}`.trim() };
  } catch (err) {
    const msg = err.message;
    skip(`Error: ${msg}`);
    return { ...base, outcome: "error", message: msg };
  } finally {
    const plans = load2();
    const p = plans.find((x) => x.id === plan.id);
    if (p) {
      p.lastRunAt = now.toISOString();
      save2(plans);
    }
  }
}
async function runDue(now = /* @__PURE__ */ new Date()) {
  const out = [];
  for (const p of load2().filter((x) => isDue(x, now))) out.push(await runPlan(p, now));
  return out;
}

// src/portfolio.ts
import { formatUnits as formatUnits3 } from "viem";
var FILE3 = dataPath("portfolio.json");
var DEFAULTS = { targets: {}, driftThresholdPct: 5, minTradeUsd: 1 };
var cents = (n) => Math.round(n * 100) / 100;
var getPortfolioConfig = () => ({ ...DEFAULTS, ...readJson(FILE3, {}) });
function setTargets(targets, driftThresholdPct = 5, minTradeUsd = 1) {
  const clean = {};
  for (const [sym, pct] of Object.entries(targets)) {
    const s = sym.trim().toUpperCase();
    if (!/^[A-Z0-9.]{1,10}$/.test(s)) throw new Error(`Invalid symbol: ${sym}`);
    if (!(pct > 0 && pct <= 100)) throw new Error(`Target for ${s} must be between 0 and 100.`);
    clean[s] = pct;
  }
  const sum = Object.values(clean).reduce((a, b) => a + b, 0);
  if (sum > 100 + 1e-9) throw new Error(`Targets add up to ${sum}%, which is over 100%.`);
  if (!(driftThresholdPct >= 0.5 && driftThresholdPct <= 50)) throw new Error("Drift threshold must be between 0.5 and 50 percentage points.");
  const cfg = { targets: clean, driftThresholdPct, minTradeUsd: Math.max(0.01, minTradeUsd) };
  writeJson(FILE3, cfg);
  bumpVersion();
  return cfg;
}
function planRebalance(holdingsUsd, cashUsd, cfg) {
  const symbols = Object.keys(cfg.targets);
  const invested = symbols.reduce((s, k) => s + (holdingsUsd[k] ?? 0), 0);
  const totalUsd = cashUsd + invested;
  const targetSum = symbols.reduce((s, k) => s + cfg.targets[k], 0);
  const cashTargetPct = 100 - targetSum;
  const pct = (v) => totalUsd > 0 ? v / totalUsd * 100 : 0;
  const rows = symbols.map((symbol) => {
    const valueUsd = holdingsUsd[symbol] ?? 0;
    const currentPct = pct(valueUsd);
    return { symbol, valueUsd: cents(valueUsd), currentPct, targetPct: cfg.targets[symbol], driftPct: currentPct - cfg.targets[symbol] };
  });
  const sells = [];
  let buys = [];
  for (const r of rows) {
    if (Math.abs(r.driftPct) < cfg.driftThresholdPct) continue;
    const diffUsd = totalUsd * r.targetPct / 100 - r.valueUsd;
    const amountUsd = cents(Math.abs(diffUsd));
    if (amountUsd < cfg.minTradeUsd) continue;
    if (diffUsd < 0) sells.push({ side: "sell", symbol: r.symbol, amountUsd });
    else buys.push({ side: "buy", symbol: r.symbol, amountUsd });
  }
  const available = cashUsd + sells.reduce((s, t) => s + t.amountUsd, 0);
  const wanted = buys.reduce((s, t) => s + t.amountUsd, 0);
  if (wanted > available && wanted > 0) {
    const k = available / wanted;
    buys = buys.map((t) => ({ ...t, amountUsd: cents(t.amountUsd * k) })).filter((t) => t.amountUsd >= cfg.minTradeUsd);
  }
  return { totalUsd: cents(totalUsd), cashUsd: cents(cashUsd), cashPct: pct(cashUsd), cashTargetPct, rows, trades: [...sells, ...buys] };
}
async function snapshot(symbols) {
  const quotes = await Promise.all(symbols.map((s) => getQuote(s)));
  const holdingsUsd = {};
  const owner = walletAddress();
  if (!owner) throw new Error(isUser() ? "Connect your wallet on the dashboard to see your live portfolio." : "AGENT_PRIVATE_KEY is not set, so the wallet cannot be read.");
  const usdg = await balanceOf(ADDR.usdg, owner);
  for (const q of quotes) {
    if (!q.contract) throw new Error(`${q.symbol} has no Robinhood Chain deployment.`);
    holdingsUsd[q.symbol] = Number(formatUnits3(await balanceOf(q.contract, owner), 18)) * q.mid;
  }
  return { source: "onchain", holdingsUsd, cashUsd: Number(formatUnits3(usdg, 6)) };
}
var viewCache = null;
async function portfolioView() {
  const cfg = getPortfolioConfig();
  const symbols = Object.keys(cfg.targets);
  if (!symbols.length) return { cfg, source: "onchain", plan: null };
  if (!isRemote() && viewCache && viewCache.version === getVersion() && Date.now() - viewCache.at < 2e4) return viewCache.value;
  const snap = await snapshot(symbols);
  const value = { cfg, source: snap.source, plan: planRebalance(snap.holdingsUsd, snap.cashUsd, cfg) };
  viewCache = { at: Date.now(), version: getVersion(), value };
  return value;
}
var clearPortfolioCache = () => viewCache = null;
async function runRebalance() {
  const cfg = getPortfolioConfig();
  const symbols = Object.keys(cfg.targets);
  if (!symbols.length) return { message: "No targets set. Set target percentages first.", results: [] };
  clearPortfolioCache();
  const snap = await snapshot(symbols);
  const plan = planRebalance(snap.holdingsUsd, snap.cashUsd, cfg);
  if (!plan.trades.length) {
    const msg = `Portfolio is within ${cfg.driftThresholdPct} points of target. No trades needed.`;
    record({
      module: "rebalance",
      action: "Rebalance check",
      verdict: "allow",
      executed: false,
      rule: `Within the ${cfg.driftThresholdPct}-point drift threshold.`,
      reasoning: "No trades needed."
    });
    return { message: msg, plan, results: [] };
  }
  const table = plan.rows.map((r) => `${r.symbol}: ${r.currentPct.toFixed(1)}% vs target ${r.targetPct}%`).join("; ");
  const tradeText = plan.trades.map((t) => `${t.side} $${t.amountUsd} ${t.symbol}`).join(", ");
  const why = await explain(`Portfolio rebalance. ${table}; cash ${plan.cashPct.toFixed(1)}% vs target ${plan.cashTargetPct.toFixed(1)}%. Planned trades: ${tradeText}. These trades bring each drifting asset back to its target weight.`);
  const results = [];
  for (const trade of plan.trades) {
    results.push({ trade, result: await requestTrade({ ...trade, module: "rebalance", why }) });
  }
  clearPortfolioCache();
  return { message: `Rebalance: ${tradeText}.`, plan, results };
}
var lastAutoRebalanceCheck = 0;
async function runRebalanceIfDue() {
  const cfg = getPortfolioConfig();
  if (!Object.keys(cfg.targets).length) return null;
  const hours = Number(process.env.REBALANCE_CHECK_HOURS) || 24;
  if (Date.now() - lastAutoRebalanceCheck < hours * 36e5) return null;
  lastAutoRebalanceCheck = Date.now();
  return runRebalance();
}

// src/research.ts
var SYSTEM3 = "You help someone research a tokenized stock before they decide whether to dollar-cost-average into it or add it to their portfolio targets. You are given its current quote. In 2-3 plain sentences, describe where the price sits in today's range and note anything relevant, such as a trading halt or a missing onchain pool. Never recommend buying or selling, never give a price target or prediction, and say plainly that this is not financial advice.";
async function researchAsset(symbol) {
  const quote = await getQuote(symbol);
  let tradable = false;
  let poolNote = "No Robinhood Chain deployment was found for this symbol.";
  if (quote.contract) {
    try {
      await quoteBuy(quote.contract, 1, quote.mid);
      tradable = true;
      poolNote = "A live Uniswap v3 pool against USDG was found on Robinhood Chain.";
    } catch (err) {
      poolNote = `No live pool was found on Robinhood Chain (${err.message}).`;
    }
  }
  const context = `Symbol: ${quote.symbol}. Bid ${quote.bid}, ask ${quote.ask}, mid ${quote.mid}. Today's range: ${quote.dailyLow} to ${quote.dailyHigh}. ${quote.halted ? "Trading is currently halted." : "Trading normally."} ${poolNote}`;
  const reply = await ask(SYSTEM3, context, { maxTokens: 220 });
  const note = usableExplanation(reply) ? reply : context;
  return {
    symbol: quote.symbol,
    quote: { bid: quote.bid, ask: quote.ask, mid: quote.mid, dailyHigh: quote.dailyHigh, dailyLow: quote.dailyLow, halted: quote.halted, generatedAt: quote.generatedAt },
    contract: quote.contract,
    tradable,
    note
  };
}

// src/registry.ts
var REGISTRY_URL = "https://api.robinhood.com/rhj/assets";
var CACHE_TTL_MS = 36e5;
var cache = null;
async function listRegistry() {
  if (cache && Date.now() - cache.at < CACHE_TTL_MS) return cache.assets;
  const res = await fetchWithRetry(REGISTRY_URL);
  if (!res.ok) throw new Error(`Robinhood's asset registry returned ${res.status}.`);
  const body = await res.json();
  const assets = (body.assets ?? []).filter((a) => a.status === "ASSET_STATUS_ACTIVE" && a.deployments.some((d) => d.chainId === 4663)).map((a) => ({
    symbol: a.tokenSymbol.toUpperCase(),
    name: a.tokenName.replace(/\s*•\s*Robinhood Token\s*$/i, "").trim(),
    contract: a.deployments.find((d) => d.chainId === 4663).contractAddress
  })).sort((x, y) => x.symbol.localeCompare(y.symbol));
  cache = { at: Date.now(), assets };
  return assets;
}

// src/walletSign.ts
import { encodeFunctionData, erc20Abi as erc20Abi3, formatEther, formatUnits as formatUnits4, getAddress, isAddress, parseUnits as parseUnits4 } from "viem";
var CHAIN_ID = 4663;
var PREPARE_TTL_MS = 10 * 6e4;
var PREPARED_FILE = dataPath("prepared.json");
var loadPrepared = () => readJson(PREPARED_FILE, {});
var savePrepared = (all) => writeJson(PREPARED_FILE, all);
var approveStep = (token, spender, amount, label) => ({
  label,
  to: token,
  data: encodeFunctionData({ abi: erc20Abi3, functionName: "approve", args: [spender, amount] })
});
var transferStep = (token, to, amount, label) => ({
  label,
  to: token,
  data: encodeFunctionData({ abi: erc20Abi3, functionName: "transfer", args: [to, amount] })
});
var swapStep = (tokenIn, tokenOut, fee, recipient, amountIn, amountOutMinimum, label) => ({
  label,
  to: ADDR.swapRouter02,
  data: encodeFunctionData({ abi: routerAbi, functionName: "exactInputSingle", args: [{ tokenIn, tokenOut, fee, recipient, amountIn, amountOutMinimum, sqrtPriceLimitX96: 0n }] })
});
var signingAvailable = () => config.live;
var short = (a) => `${a.slice(0, 6)}\u2026${a.slice(-4)}`;
var allowanceOf = (token, owner, spender) => mainnetClient.readContract({ address: token, abi: erc20Abi3, functionName: "allowance", args: [owner, spender] });
function parseAccount(account) {
  if (typeof account !== "string" || !isAddress(account)) throw new Error("That is not a valid wallet address.");
  return getAddress(account);
}
async function walletBalances(account) {
  const a = parseAccount(account);
  const [usdg, eth] = await Promise.all([balanceOf(ADDR.usdg, a), mainnetClient.getBalance({ address: a })]);
  return { usdg: formatUnits4(usdg, 6), eth: formatEther(eth) };
}
function pruned(all) {
  const now = Date.now();
  return Object.fromEntries(Object.entries(all).filter(([, p]) => p.expiresAt >= now));
}
async function prepareTrade(t, account) {
  const verdict = evaluate({ ...policy(), approvalThreshold: Infinity }, { amountUsd: t.amountUsd }, spentToday(readAll()), /* @__PURE__ */ new Set());
  if (verdict.decision === "deny") throw new Error(`Blocked by your rules: ${verdict.reason}`);
  const q = await getQuote(t.symbol);
  if (q.halted) throw new Error(`${t.symbol} trading is halted right now.`);
  if (!q.contract) throw new Error(`${t.symbol} has no Robinhood Chain deployment.`);
  const token = q.contract;
  if (t.side === "buy") {
    const amountIn2 = parseUnits4(t.amountUsd.toString(), 6);
    const [bal, allowed2] = await Promise.all([balanceOf(ADDR.usdg, account), allowanceOf(ADDR.usdg, account, ADDR.swapRouter02)]);
    if (bal < amountIn2) throw new Error(`Your wallet holds ${formatUnits4(bal, 6)} USDG, but this buy needs ${t.amountUsd}.`);
    const route3 = await quoteBuy(token, t.amountUsd, q.ask);
    const steps2 = [];
    if (allowed2 < amountIn2) steps2.push(approveStep(ADDR.usdg, ADDR.swapRouter02, amountIn2, "Approve USDG"));
    steps2.push(swapStep(ADDR.usdg, token, route3.fee, account, amountIn2, minOut(route3.amountOut, config.slippageBps), `Buy ${t.symbol}`));
    const detail2 = `~${route3.tokens.toFixed(6)} tokens via ${route3.fee / 1e4}% pool @ $${route3.impliedPriceUsd.toFixed(2)}`;
    return { steps: steps2, summary: `Buy $${t.amountUsd} of ${t.symbol}, ${detail2}`, action: `Buy ${t.symbol}: ${detail2}` };
  }
  const held = await balanceOf(token, account);
  const wanted = parseUnits4((t.amountUsd / q.mid).toFixed(18), 18);
  const amountIn = held < wanted ? held : wanted;
  if (amountIn <= 0n) throw new Error(`Your wallet holds no ${t.symbol}.`);
  const route2 = await quoteSell(token, amountIn, q.bid);
  const allowed = await allowanceOf(token, account, ADDR.swapRouter02);
  const steps = [];
  if (allowed < amountIn) steps.push(approveStep(token, ADDR.swapRouter02, amountIn, `Approve ${t.symbol}`));
  steps.push(swapStep(token, ADDR.usdg, route2.fee, account, amountIn, minOut(route2.amountOut, config.slippageBps), `Sell ${t.symbol}`));
  const detail = `~${formatUnits4(amountIn, 18).slice(0, 10)} tokens for ~$${route2.usdOut.toFixed(2)} via ${route2.fee / 1e4}% pool`;
  return { steps, summary: `Sell ${detail}`, action: `Sell ${t.symbol}: ${detail}` };
}
async function preparePayment(req, account) {
  const verdict = evaluate({ ...policy(), approvalThreshold: Infinity }, req, spentToday(readAll()), payeeSet());
  if (verdict.decision === "deny") throw new Error(`Blocked by your rules: ${verdict.reason}`);
  const token = config.paymentToken ?? ADDR.usdg;
  const amount = parseUnits4(req.amountUsd.toString(), config.paymentDecimals);
  const bal = await balanceOf(token, account);
  if (bal < amount) throw new Error(`Your wallet holds ${formatUnits4(bal, config.paymentDecimals)} USDG, but this payment needs ${req.amountUsd}.`);
  return { steps: [transferStep(token, getAddress(req.to), amount, `Pay ${short(req.to)}`)], summary: `Pay $${req.amountUsd} to ${short(req.to)} (${req.memo})`, action: req.memo };
}
async function prepareSigned(id, accountInput) {
  if (!signingAvailable()) throw new Error("Signing with your wallet needs trading switched on (NETWORK=mainnet and LIVE_MAINNET=yes).");
  const account = parseAccount(accountInput);
  const p = getPending(id);
  if (!p) throw new Error("That action no longer exists or has expired.");
  const built = p.kind === "trade" ? await prepareTrade(p.trade, account) : await preparePayment(p.req, account);
  const entry2 = p.kind === "trade" ? { module: p.trade.module, action: built.action, amountUsd: p.trade.amountUsd, why: p.trade.why } : { module: p.req.module, action: built.action, amountUsd: p.req.amountUsd, to: p.req.to, why: "Held for approval, then signed by the owner." };
  savePrepared({ ...pruned(loadPrepared()), [id]: { account, steps: built.steps, expiresAt: Date.now() + PREPARE_TTL_MS, entry: entry2 } });
  return { steps: built.steps, summary: built.summary, chainId: CHAIN_ID };
}
function forget(id) {
  const all = loadPrepared();
  delete all[id];
  savePrepared(all);
}
var isHash = (h) => typeof h === "string" && /^0x[0-9a-fA-F]{64}$/.test(h);
async function completeSigned(id, accountInput, hashes) {
  const account = parseAccount(accountInput);
  const prep = loadPrepared()[id];
  if (!prep || prep.expiresAt < Date.now()) throw new Error("This signing session expired. Press the button again to prepare it.");
  if (prep.account !== account) throw new Error("A different wallet was prepared for this action.");
  if (!Array.isArray(hashes) || !hashes.length || hashes.length > 3 || !hashes.every(isHash)) throw new Error("Expected 1 to 3 transaction hashes.");
  const mainHash = hashes[hashes.length - 1];
  const mainStep = prep.steps[prep.steps.length - 1];
  let receipt;
  try {
    receipt = await mainnetClient.waitForTransactionReceipt({ hash: mainHash, timeout: 3e4 });
  } catch {
    return { status: "pending", message: "Not confirmed on the chain yet. It will be recorded once it is.", txHash: mainHash };
  }
  const tx = await mainnetClient.getTransaction({ hash: mainHash });
  if (tx.from.toLowerCase() !== account.toLowerCase()) throw new Error("That transaction was not sent from the connected wallet.");
  if (tx.to?.toLowerCase() !== mainStep.to.toLowerCase() || tx.input.toLowerCase() !== mainStep.data.toLowerCase()) {
    throw new Error("That transaction does not match what was prepared, so it was not recorded.");
  }
  if (receipt.status !== "success") {
    const { why: _why, ...base } = prep.entry;
    record({ ...base, verdict: "needs_approval", executed: false, txHash: mainHash, reasoning: `Signed by ${short(account)} but the transaction reverted on chain.` });
    forget(id);
    throw new Error("The transaction reverted on chain. Nothing was bought or paid; only gas was used.");
  }
  takePending(id);
  const { why, ...entry2 } = prep.entry;
  record({ ...entry2, verdict: "needs_approval", executed: true, txHash: mainHash, reasoning: `${why} Signed with the owner's wallet ${short(account)}.` });
  forget(id);
  bumpVersion();
  return { status: "executed", message: `Confirmed on chain. ${prep.entry.action}`, txHash: mainHash };
}

// src/dashboard.ts
var WEB = resolve(fileURLToPath2(new URL("../web/", import.meta.url)));
var address = z.string().regex(/^0x[0-9a-fA-F]{40}$/, "Must be a 0x EVM address");
var bodies = {
  dca: z.object({ symbol: z.string(), amountUsd: z.number().positive(), intervalHours: z.number().min(1) }),
  cancel: z.object({ id: z.string() }),
  payee: z.object({ address, label: z.string().min(1).max(60) }),
  pay: z.object({ module: z.enum(["payroll", "bills"]), to: address, amountUsd: z.number().positive(), memo: z.string().max(120) }),
  id: z.object({ id: z.string() }),
  targets: z.object({ targets: z.record(z.string(), z.number()), driftThresholdPct: z.number().optional() }),
  prepare: z.object({ id: z.string(), account: z.string() }),
  complete: z.object({ id: z.string(), account: z.string(), hashes: z.array(z.string()).min(1).max(3) }),
  linkWallet: z.object({ address }),
  confirm: z.object({ password: z.string().min(1).max(128) }),
  signup: z.object({ username: z.string(), password: z.string(), accept: z.literal(true, { errorMap: () => ({ message: "Please confirm that you understand the risks." }) }) }),
  signin: z.object({ username: z.string(), password: z.string() })
};
var PROFILE = dataPath("profile.json");
var EXPLORER = config.network === "mainnet" ? "https://robinhoodchain.blockscout.com/tx/" : "https://explorer.testnet.chain.robinhood.com/tx/";
async function state() {
  const entries = readAll();
  return {
    network: config.network,
    live: config.live,
    offReason: tradingOffReason,
    signing: signingAvailable(),
    hosted: hosted(),
    user: isUser() ? { username: readJson(PROFILE, {}).username ?? null } : null,
    store: backendName(),
    explorer: EXPLORER,
    wallet: walletAddress() ?? null,
    balance: await tokenBalance().catch(() => "unavailable"),
    policy: policy(),
    spentToday: spentToday(entries),
    payees: listPayees(),
    pending: listPending().map((p) => {
      const expiresAt = new Date(new Date(p.createdAt).getTime() + APPROVAL_TTL_MS).toISOString();
      return p.kind === "pay" ? { id: p.id, kind: p.kind, module: p.req.module, amountUsd: p.req.amountUsd, label: p.req.memo, to: p.req.to, createdAt: p.createdAt, expiresAt } : { id: p.id, kind: p.kind, module: p.trade.module, amountUsd: p.trade.amountUsd, label: `${p.trade.side === "buy" ? "Buy" : "Sell"} ${p.trade.symbol}`, to: "", createdAt: p.createdAt, expiresAt };
    }),
    portfolio: await portfolioView().catch((e) => ({ error: e.message })),
    plans: listPlans(),
    ledger: entries.slice(-200).reverse()
  };
}
var CSP = "default-src 'none'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'";
function baseHeaders(type, cache2) {
  return { "content-type": type, "cache-control": cache2, "x-content-type-options": "nosniff", "content-security-policy": CSP, "referrer-policy": "no-referrer" };
}
function send(res, code, body) {
  res.writeHead(code, baseHeaders("application/json; charset=utf-8", "no-store"));
  res.end(JSON.stringify(body));
}
var TYPES = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8"
};
function serveStatic(res, urlPath) {
  const map = { "/": "index.html", "/app": "app.html", "/app/": "app.html", "/login": "login.html", "/me": "app.html", "/account": "account.html" };
  const rel = map[urlPath] ?? decodeURIComponent(urlPath).replace(/^\/+/, "");
  const file = resolve(WEB, rel);
  const inside = relative(WEB, file);
  if (inside.startsWith("..") || isAbsolute(inside) || !TYPES[extname(file)]) return false;
  if (!existsSync3(file) || !statSync(file).isFile()) return false;
  const ext = extname(file);
  res.writeHead(200, baseHeaders(TYPES[ext], ext === ".woff2" ? "public, max-age=31536000, immutable" : "no-cache"));
  res.end(readFileSync3(join2(WEB, inside)));
  return true;
}
async function readJson2(req) {
  const parsed = req.body;
  if (parsed !== void 0 && parsed !== null) {
    if (Buffer.isBuffer(parsed)) return JSON.parse(parsed.toString("utf8") || "{}");
    if (typeof parsed === "string") return JSON.parse(parsed || "{}");
    return parsed;
  }
  let size = 0;
  const chunks = [];
  for await (const c of req) {
    size += c.length;
    if (size > 1e4) throw new Error("Body too large");
    chunks.push(c);
  }
  return JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}");
}
async function login(req, res, secure) {
  const problem = authConfigProblem();
  if (problem) return send(res, 503, { error: problem });
  if (!authRequired()) return send(res, 200, { ok: true });
  if (!req.headers["content-type"]?.startsWith("application/json")) return send(res, 415, { error: "JSON only" });
  if (!sameOrigin(req)) return send(res, 403, { error: "Cross-site request refused" });
  if (!await withinRateLimit("login:" + clientId(req), 8, 60)) return send(res, 429, { error: "Too many attempts. Wait a minute and try again." });
  const body = await readJson2(req);
  if (!checkPassword(body.password)) {
    await new Promise((r) => setTimeout(r, 400));
    return send(res, 401, { error: "Wrong password." });
  }
  res.setHeader("set-cookie", sessionCookie(makeToken(), secure));
  send(res, 200, { ok: true });
}
async function cron(req, res) {
  if (!cronAuthorized(req)) return send(res, 401, { error: "Unauthorized" });
  const { dca, rebalance } = await withStore(async () => {
    const dca2 = await runDue();
    let rebalance2 = null;
    try {
      rebalance2 = await runRebalanceIfDue();
    } catch (err) {
      rebalance2 = { message: `Rebalance check failed: ${err.message}`, results: [] };
    }
    return { dca: dca2, rebalance: rebalance2 };
  }, { lock: true });
  send(res, 200, {
    ran: dca.length,
    results: dca.map((r) => ({ symbol: r.symbol, outcome: r.outcome })),
    rebalance: rebalance ? { message: rebalance.message, trades: rebalance.results.length } : null
  });
}
var RESEARCH_MAX_PER_DAY = Number(process.env.RESEARCH_MAX_PER_DAY) || 100;
var QUOTES_MAX_PER_DAY = Number(process.env.QUOTES_MAX_PER_DAY) || 2e3;
async function route(req, res, method, path, url) {
  if (method === "GET" && path === "/api/state") return send(res, 200, await state());
  if (method === "GET" && path === "/api/wallet") return send(res, 200, await walletBalances(url.searchParams.get("account") ?? ""));
  if (method === "GET" && path === "/api/portfolio/config") return send(res, 200, getPortfolioConfig());
  if (method === "GET" && path === "/api/registry") return send(res, 200, { assets: await listRegistry() });
  if (method === "GET" && path === "/api/quotes") {
    const symbols = [...new Set((url.searchParams.get("symbols") ?? "").split(",").map((s) => s.trim().toUpperCase()).filter(Boolean))].slice(0, 40);
    if (!symbols.length) return send(res, 400, { error: "symbols is required." });
    const key = "quotes:" + (currentTenant()?.id ?? "owner");
    if (!await withinRateLimit(key, QUOTES_MAX_PER_DAY, 86400)) return send(res, 429, { error: "Quote lookups are limited per day. Try again tomorrow." });
    const quotes = await Promise.all(
      symbols.map(async (symbol) => {
        try {
          const q = await getQuote(symbol);
          return { symbol: q.symbol, ok: true, bid: q.bid, ask: q.ask, mid: q.mid, dailyLow: q.dailyLow, dailyHigh: q.dailyHigh, halted: q.halted };
        } catch (err) {
          return { symbol, ok: false, error: err.message };
        }
      })
    );
    return send(res, 200, { quotes });
  }
  if (method === "GET" && path === "/api/research") {
    const symbol = (url.searchParams.get("symbol") ?? "").trim();
    if (!symbol) return send(res, 400, { error: "Symbol is required." });
    const key = "research:" + (currentTenant()?.id ?? "owner");
    if (!await withinRateLimit(key, RESEARCH_MAX_PER_DAY, 86400)) return send(res, 429, { error: "Research lookups are limited per day. Try again tomorrow." });
    return send(res, 200, await researchAsset(symbol));
  }
  if (method === "POST") {
    if (!req.headers["content-type"]?.startsWith("application/json")) return send(res, 415, { error: "JSON only" });
    const raw = await readJson2(req);
    switch (path) {
      case "/api/dca": {
        const b = bodies.dca.parse(raw);
        return send(res, 200, createPlan(b.symbol, b.amountUsd, b.intervalHours));
      }
      case "/api/dca/run":
        return send(res, 200, await runDue());
      case "/api/dca/cancel":
        return send(res, 200, { ok: cancelPlan(bodies.cancel.parse(raw).id) });
      case "/api/payee": {
        const b = bodies.payee.parse(raw);
        addPayee(b.address, b.label);
        return send(res, 200, { ok: true });
      }
      case "/api/pay": {
        const b = bodies.pay.parse(raw);
        return send(res, 200, await pay({ module: b.module, to: b.to, amountUsd: b.amountUsd, memo: b.memo || "Manual payment" }));
      }
      case "/api/portfolio/targets": {
        const b = bodies.targets.parse(raw);
        return send(res, 200, setTargets(b.targets, b.driftThresholdPct));
      }
      case "/api/portfolio/rebalance":
        return send(res, 200, await runRebalance());
      case "/api/approve":
        return send(res, 200, await approveAny(bodies.id.parse(raw).id));
      case "/api/wallet/prepare": {
        const b = bodies.prepare.parse(raw);
        return send(res, 200, await prepareSigned(b.id, b.account));
      }
      case "/api/wallet/complete": {
        const b = bodies.complete.parse(raw);
        return send(res, 200, await completeSigned(b.id, b.account, b.hashes));
      }
      case "/api/reject":
        return send(res, 200, rejectAny(bodies.id.parse(raw).id));
      case "/api/account/wallet": {
        if (!isUser()) return send(res, 403, { error: "Only for accounts." });
        const b = bodies.linkWallet.parse(raw);
        writeJson(PROFILE, { ...readJson(PROFILE, {}), wallet: getAddress2(b.address) });
        return send(res, 200, { ok: true });
      }
    }
  }
  send(res, 404, { error: "Not found" });
}
async function signup(req, res, secure) {
  if (!usersEnabled()) return send(res, 404, { error: "Accounts are not switched on for this site." });
  if (!req.headers["content-type"]?.startsWith("application/json")) return send(res, 415, { error: "JSON only" });
  if (!sameOrigin(req)) return send(res, 403, { error: "Cross-site request refused" });
  const b = bodies.signup.parse(await readJson2(req));
  validatePassword(b.password, validateUsername(b.username));
  const allowed = await signupAllowed(clientId(req));
  if (!allowed.ok) return send(res, 429, { error: allowed.message });
  const { id, username } = await createAccount(b.username, b.password);
  await withStore(async () => writeJson(PROFILE, { username, acceptedAt: (/* @__PURE__ */ new Date()).toISOString() }), { lock: true, tenant: { kind: "user", id } });
  res.setHeader("set-cookie", userCookie(makeUserToken(id), secure));
  send(res, 200, { ok: true });
}
async function signin(req, res, secure) {
  if (!usersEnabled()) return send(res, 404, { error: "Accounts are not switched on for this site." });
  if (!req.headers["content-type"]?.startsWith("application/json")) return send(res, 415, { error: "JSON only" });
  if (!sameOrigin(req)) return send(res, 403, { error: "Cross-site request refused" });
  const b = bodies.signin.parse(await readJson2(req));
  if (!await loginAllowed(clientId(req), b.username)) return send(res, 429, { error: "Too many attempts. Wait a few minutes and try again." });
  const who = await checkLogin(b.username, b.password);
  if (!who) {
    await new Promise((r) => setTimeout(r, 300));
    return send(res, 401, { error: "Wrong username or password." });
  }
  res.setHeader("set-cookie", userCookie(makeUserToken(who.id), secure));
  send(res, 200, { ok: true });
}
async function deleteAccount(req, res, tenant, secure) {
  if (!req.headers["content-type"]?.startsWith("application/json")) return send(res, 415, { error: "JSON only" });
  const { password } = bodies.confirm.parse(await readJson2(req));
  const profile = await withStore(async () => readJson(PROFILE, {}), { tenant });
  const who = profile.username ? await checkLogin(profile.username, password) : null;
  if (!who || who.id !== tenant.id) return send(res, 403, { error: "Wrong password." });
  await removeAccount(who.username, tenant.id);
  res.setHeader("set-cookie", clearedUserCookie(secure));
  send(res, 200, { ok: true });
}
async function userRoute(req, res, method, path, url, secure) {
  if (!usersEnabled()) return send(res, 404, { error: "Accounts are not switched on for this site." });
  const id = userIdFrom(req);
  if (!id) return send(res, 401, { error: "Sign in first.", code: "signin_required" });
  if (method !== "GET" && !sameOrigin(req)) return send(res, 403, { error: "Cross-site request refused" });
  const tenant = { kind: "user", id };
  if (method === "POST" && path === "/api/account/delete") return await deleteAccount(req, res, tenant, secure);
  if (!USER_ALLOWED.has(`${method} ${path}`)) return send(res, 403, { error: "That is not available for accounts." });
  if ((method === "POST" || path === "/api/wallet") && !await withinRateLimit("acct-act:" + id, USER_LIMITS.actionsPerDay, 86400)) return send(res, 429, { error: "Daily action limit reached. Try again tomorrow." });
  return await withStore(
    async () => {
      if (!readJson(PROFILE, {}).username) {
        res.setHeader("set-cookie", clearedUserCookie(secure));
        return send(res, 401, { error: "Sign in first.", code: "signin_required" });
      }
      return route(req, res, method, path, url);
    },
    { lock: method !== "GET", tenant }
  );
}
async function handleRequest(req, res, opts) {
  try {
    if (opts.allowedHosts && !opts.allowedHosts.has(req.headers.host ?? "")) return send(res, 403, { error: "Forbidden host" });
    const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);
    const path = url.pathname;
    const method = req.method ?? "GET";
    const secure = hosted() || req.headers["x-forwarded-proto"] === "https";
    const userMode = req.headers["x-ledgerly-mode"] === "user";
    if (method === "GET" && path === "/api/health") return send(res, 200, { ok: true });
    if (method === "GET" && path === "/api/session") {
      if (userMode) {
        const uid = usersEnabled() ? userIdFrom(req) : null;
        const active = uid ? await withStore(async () => Boolean(readJson(PROFILE, {}).username), { tenant: { kind: "user", id: uid } }) : false;
        if (uid && !active) res.setHeader("set-cookie", clearedUserCookie(secure));
        return send(res, 200, { user: { enabled: usersEnabled(), active } });
      }
      return send(res, 200, { authRequired: authRequired(), authed: !authRequired() || isAuthed(req), accountsEnabled: usersEnabled() });
    }
    if (method === "POST" && path === "/api/signup") return await signup(req, res, secure);
    if (method === "POST" && path === "/api/signin") return await signin(req, res, secure);
    if (method === "POST" && path === "/api/signout") {
      res.setHeader("set-cookie", clearedUserCookie(secure));
      return send(res, 200, { ok: true });
    }
    if (method === "POST" && path === "/api/login") return await login(req, res, secure);
    if (method === "POST" && path === "/api/logout") {
      res.setHeader("set-cookie", clearedCookie(secure));
      return send(res, 200, { ok: true });
    }
    if (path === "/api/cron") return await cron(req, res);
    if (method === "GET" && !path.startsWith("/api/") && opts.serveFiles && serveStatic(res, path)) return;
    if (!path.startsWith("/api/")) return send(res, 404, { error: "Not found" });
    if (userMode) return await userRoute(req, res, method, path, url, secure);
    const problem = authConfigProblem();
    if (problem) return send(res, 503, { error: problem });
    if (authRequired()) {
      if (!isAuthed(req)) return send(res, 401, { error: "Sign in required" });
      if (method !== "GET" && !sameOrigin(req)) return send(res, 403, { error: "Cross-site request refused" });
    }
    return await withStore(() => route(req, res, method, path, url), { lock: method !== "GET" });
  } catch (err) {
    if (res.headersSent) return void res.end();
    const msg = err instanceof z.ZodError ? err.issues.map((i) => i.message).join("; ") : err.message;
    send(res, 400, { error: msg });
  }
}
function startDashboard(port = Number(process.env.DASHBOARD_PORT) || 3e3) {
  const allowedHosts = /* @__PURE__ */ new Set([`localhost:${port}`, `127.0.0.1:${port}`]);
  const server = createServer((req, res) => void handleRequest(req, res, { serveFiles: true, allowedHosts }));
  server.listen(port, "127.0.0.1", () => {
    console.log(`Ledgerly dashboard: http://localhost:${port}`);
    if (authRequired()) console.log("Login is on (DASHBOARD_PASSWORD is set).");
    if (tradingOffReason) console.warn(`Trading is OFF: ${tradingOffReason}`);
    else console.warn(`LIVE on ${config.network}: transactions use real funds.`);
  });
  return server;
}
export {
  handleRequest,
  startDashboard
};
